# Generated by Django 3.0.2 on 2020-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=4, max_digits=10)),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
            ],
        ),
    ]
