# Generated by Django 3.0.3 on 2020-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_exc_vat", models.DecimalField(decimal_places=4, max_digits=10)),
                ("value_inc_vat", models.DecimalField(decimal_places=4, max_digits=10)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
            ],
            options={
                "ordering": ["-valid_to"],
            },
        ),
        migrations.AlterModelOptions(
            name="consumption",
            options={"ordering": ["-interval_end"]},
        ),
    ]
