# Generated by Django 3.0.3 on 2020-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_auto_20201003_1449"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasConsumption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("consumption", models.DecimalField(decimal_places=4, max_digits=10)),
                ("interval_start", models.DateTimeField()),
                ("interval_end", models.DateTimeField()),
            ],
            options={
                "ordering": ["-interval_end"],
                "abstract": False,
            },
        ),
    ]
